<a href="https://colab.research.google.com/github/UpendraVishwanathYS/IISc_Deep_Learning_Course_Assignment/blob/main/M1_AST_02_Linear_Algebra_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Programme in Deep Learning (Foundations and Applications)
## A Program by IISc and TalentSprint
### Assignment 2: Linear Algebra

## Learning Objectives

At the end of the assignment, you will be able to

*   solve the system of linear equation using matrix solution
*   implement concepts related to eigen vectors and values
*   understand rank of a matrix
*   implement SVD (Singular Value Decomposition) using Python
*   understand vector and matrix norm
*   perform various matrix calculus operations using Python



### Setup Steps:

In [ ]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "" #@param {type:"string"}

In [ ]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "" #@param {type:"string"}

In [1]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython
import warnings
warnings.filterwarnings("ignore")

ipython = get_ipython()

notebook= "M1_AST_02_Linear_Algebra_A" #name of the notebook

def setup():
    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getAnswer1() and getAnswer2() and getComplexity() and getAdditional() and getConcepts() and getComments() and getMentorSupport():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "answer1" : Answer1, "answer2" : Answer2, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook,
              "feedback_experiments_input" : Comments,
              "feedback_mentor_support": Mentor_support}
      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://learn-iisc.talentsprint.com/notebook_submissions")
        #print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
        return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None


# def getWalkthrough():
#   try:
#     if not Walkthrough:
#       raise NameError
#     else:
#       return Walkthrough
#   except NameError:
#     print ("Please answer Walkthrough Question")
#     return None

def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None


def getMentorSupport():
  try:
    if not Mentor_support:
      raise NameError
    else:
      return Mentor_support
  except NameError:
    print ("Please answer Mentor support Question")
    return None

def getAnswer1():
  try:
    if not Answer1:
      raise NameError
    else:
      return Answer1
  except NameError:
    print ("Please answer Question 1")
    return None

def getAnswer2():
  try:
    if not Answer2:
      raise NameError
    else:
      return Answer2
  except NameError:
    print ("Please answer Question 2")
    return None


def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()
else:
  print ("Please complete Id and Password cells before running setup")



Please complete Id and Password cells before running setup


### Importing the required libraries

In [10]:
import numpy as np
import scipy
import sympy as sym
import matplotlib.pyplot as plt
from sympy.abc import x, y,z
from scipy import linalg
from numpy.linalg import eig
import torch


### Cross Product & Dot Product of Vector and Matrices


*   **Cross Product** : In three-dimensional space, the cross product is a binary operation between two vectors. It produces a perpendicular vector to both vectors.

<center><img src="https://cdn.iisc.talentsprint.com/DLFA/Experiment_related_data/cross_product.png" alt="Drawing" height="300" width="280"/></center>

*   **Dot Product** : The dot product is defined algebraically as the sum of the products of the corresponding entries of the two number sequences. Moreover, it is the product of the Euclidean magnitudes and the cosine of the angle between them.

<br>
<center>
<img src="https://cdn.iisc.talentsprint.com/DLFA/Experiment_related_data/dot_product-01.png" alt="Drawing" height="300" width="300"/></center>


1. Create two matrices and perform cross product on them.

In [12]:
mat1 = torch.randn(3,3)
mat2 = torch.randn(3,3)
cross_product = torch.cross(mat1,mat2)
print("Cross Product:\n",cross_product)

Cross Product:
 tensor([[-0.4327,  1.7927,  1.4338],
        [ 0.2221, -2.0131,  0.1050],
        [-0.3058, -2.1318,  0.3956]])


2. Apply dot product on the below given vectors:

    i). x = sin45 i + 6j
    
    ii).   y = 42i + 7j



In [15]:
# Taking two 1D arrays
y = [42,7]
x = [np.sin(np.pi/4),6]

# Calculating dot product using dot() method
# YOUR CODE HERE
dot_product = torch.dot(torch.tensor(x,dtype=torch.float),torch.tensor(y,dtype=torch.float))
print("Dot Product:\n",dot_product)

Dot Product:
 tensor(71.6985)


3. Create two vectors and perform cross product operation on them.


In [16]:
# Creating matrices
# YOUR CODE HERE
mat1 = torch.randn(3,3)
mat2 = torch.randn(3,3)

# Cross product of matrices
# YOUR CODE HERE
cross_product = torch.cross(mat1,mat2)
print("Cross Product:\n",cross_product)

Cross Product:
 tensor([[-1.8760, -0.7952, -0.1557],
        [-0.5441, -0.9125,  2.4691],
        [ 3.7190,  1.0171,  0.6952]])


### System of Linear Equations

1. Solve the following linear equation for x and y using matrix solution.

  i). 7x + 3y = 34

  ii). 8x + 9y = 50

    Hint: Use the equation for AX = B to solve the equation where A & B are the matrices for values of LHS and RHS of the equation and X consist of x & y variables.
    
    To know more about Python libraries, [here ](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)








Steps to solve:

1. Write the equation in the form of $AX = B$
2. Then, you can write it as -> $X = A^{-1}.B$

In [22]:
# Creating matrices
# YOUR CODE HERE
A = torch.tensor([[7,3],[8,9]],dtype=torch.float)
B = torch.tensor([34,50],dtype=torch.float)

# Inverse of matrix A
# YOUR CODE HERE
A_inv = torch.inverse(A)

# Dot product of matrix A1 and B
# YOUR CODE HERE
X = torch.matmul(A_inv,B)
print("Solution:\n",X)

#verify:
B_hat = torch.matmul(A,X)
if torch.allclose(B,B_hat):
  print("Solution is correct")
else:
  print("Solution is incorrect")

Solution:
 tensor([4.0000, 2.0000])
Solution is correct


2. Find the values of x and y from the system of linear equations given below and verify the solution:

  i). 6x + 5y = 19

  ii). 7x + 9y = 32







Steps to solve:

1. Create two arrays.

2. Solve for x and y.

3. Compute the dot product of the matrix equation(array) and the solution

4. Use allclose() method to check whether the matrices are element-wise equal or not.

In [23]:
# Creating arrays
# YOUR CODE HERE
A = torch.tensor([[6,5],[7,9]],dtype=torch.float)
B = torch.tensor([19,32],dtype=torch.float)

# Inverse of matrix A
# YOUR CODE HERE
A_inv = torch.inverse(A)

# Solve a linear matrix equation
# YOUR CODE HERE
X = torch.matmul(A_inv,B)
print("Solution:\n",X)

# Verify the solution
# Creating matrices
ver_sol = torch.matmul(A,X)
if torch.allclose(B,ver_sol):
  print("Solution is correct")
else:
  print("Solution is incorrect")

Solution:
 tensor([0.5789, 3.1053])
Solution is correct


3. Below are pair of three linear equations. Find the values of x, y, & z.

  i). 8x + 3y + 5z = 29

  ii). 4x + 7y + 12z = 54

  iii). 9x + 5y + 11z = 52







In [24]:
# Creating matrices
# YOUR CODE HERE
A = torch.tensor([[8,3,5],[4,7,12],[9,5,11]],dtype=torch.float)
B = torch.tensor([29,54,52],dtype=torch.float)
# Inverse of matrix A
# YOUR CODE HERE
A_inv = torch.inverse(A)
# Dot product of A1 and B
# YOUR CODE HERE
X = torch.matmul(A_inv,B)
print("Solution:\n",X)

Solution:
 tensor([1.0000, 2.0000, 3.0000])


4. Suppose an automobile company sells 25 bikes and 32 scooties in January. In the next month the sale goes up to 30 bikes and 41 scooties. The total revenue generated is Rs. 506,000 and Rs.620,000 for the respective months.
Find the cost of bike and scooty using matrix solution.

  Hint: Form the pair of linear equations using the below problem statement and solve the equations to get the answer.

    Assume the cost of bike and scooty as x and y. Moreover, we can create the equation:

       i)   25x + 32y = 506000

       ii)  30x + 41y = 628000



In [26]:
# Create matrices using the values from the equation
# YOUR CODE HERE
A = torch.tensor([[25,32],[30,41]],dtype=torch.float)
B = torch.tensor([506000,628000],dtype=torch.float)
# Inverse of matrix A
# YOUR CODE HERE
A_inv = torch.inverse(A)
# Dot product of A1 and B
# YOUR CODE HERE
X = torch.matmul(A_inv,B)
print("Solution:\n",X)

Solution:
 tensor([10000.0186,  7999.9814])


### Checking the Linear Dependence and Independence

We use linear dependence and independence to check the relation of the variables in the real-world dataset.

1. Check linear dependence for the following equations.

  i). 6x + 3y + 5z = 19

  ii). 2x + y + 7z = 17  

  iii). 16x + 8y + 40z = 104  

  Hint : If the determinant is 0 then it is linearly dependent.





In [27]:
# Creating arrays
# YOUR CODE HERE
A = torch.tensor([[6,3,5],[2,1,7],[16,8,40]],dtype=torch.float)
B = torch.tensor([19,17,104],dtype=torch.float)
# Finding determinant
# YOUR CODE HERE
det = torch.linalg.det(A)
print("Determinant:\n",det)

# Applying condition
# YOUR CODE HERE
if det == 0:
  print("Linearly Dependent")
else:
  print("Linearly Independent")

Determinant:
 tensor(-0.)
Linearly Dependent


2. Find whether the below linear equations are linearly dependent or independent.

  i). 4x + 2y = 6

  ii). y = -x-2


In [28]:
a = np.array([[4,2],[1,1]])
print(a)
# Finding determinant
# YOUR CODE HERE
det = np.linalg.det(a)
print("Determinant:\n",det)

# Applying the condition
# YOUR CODE HERE
if det == 0:
  print("Linearly Dependent")
else:
  print("Linearly Independent")

[[4 2]
 [1 1]]
Determinant:
 2.0
Linearly Independent


### Eigen Vectors and Values

Eigen values and vectors are specifically used to define the characterstics of a matrix which is a form of representing data. So, when we train a Machine Learning or Deep Learning model there are chances where unncessary data is punched for training. Thus, using eigen vectors and values we can reduce the training data by knowing its characterstics.


**Eigen Vector**: A non-zero vector that changes by a scalar factor when a linear transformation is applied is known as an eigenvector.

**Eigen Values**: When a linear transformation is applied to an eigenvector, the eigenvector is scaled by a particular value which is called eigenvalue.

1. Create a matrix and find the eigen vectors and eigen values for it.

In [30]:
# Create a matrix
A = torch.tensor(A,dtype=torch.float)
print("Array:\n",A)
# Calculating eigen vectors and eigen values
val,vec = torch.linalg.eig(A)
print("Eigen Value:\n",val)
print("Eigen Vector:\n",vec)

Array:
 tensor([[ 6.,  3.,  5.],
        [ 2.,  1.,  7.],
        [16.,  8., 40.]])
Eigen Value:
 tensor([4.3705e+01+0.j, 3.2948e+00+0.j, 9.1396e-07+0.j])
Eigen Vector:
 tensor([[-1.4263e-01+0.j, -9.0645e-01+0.j,  4.4721e-01+0.j],
        [-1.6660e-01+0.j,  2.4944e-01+0.j, -8.9443e-01+0.j],
        [-9.7565e-01+0.j,  3.4076e-01+0.j, -9.2339e-08+0.j]])


2. Confirm that the vector for the below matrix is an eigen vector of the matrix.

  Hint: Equate the multiplication of first eigen
vector with multiplication of first eigen vector and first eigen value.






In [33]:
# Defining a matrix
M = np.array([[3,2,7],[5,8,9],[9,3,7]])

# Finding eigen vectors and values
val,vec = torch.linalg.eig(torch.tensor(M,dtype=torch.float))

# Finding first vector
N = vec[:,0]
print("First Vector:\n", N)

# Finding second vector
P = vec[:1]
print("Second Vector:\n",P)

First Vector:
 tensor([-0.3767+0.j, -0.7443+0.j, -0.5514+0.j])
Second Vector:
 tensor([[-0.3767+0.j, -0.6923+0.j,  0.2117+0.j]])


3. Create a matrix and try to reconstruct the original matrix using the eigen values and vectors.

 Steps to reconstruct the matrix using eigen values and vectors:

  i).  Create inverse of eigen vector matrix

  ii). Create diagonal matrix from eigen values

  iii). Get the original matrix by dot product of eigen vector matrix, diagonal matrix, and inverse of eigen vector matrix.






In [37]:
# Defining matrix
M = np.array([[6, 8, 5], [4, 7, 1], [9, 2, 6]])
print("Initial Matrix:\n",M)
val, vec = torch.linalg.eig(torch.tensor(M,dtype=torch.float))
print("Eigen Values:\n",val)
print("Eigen Vectors:\n",vec)

# Create matrix from eigenvectors
P = vec

# Create inverse of eigenvectors matrix
Q = torch.inverse(torch.tensor(P,dtype=torch.float))

# Create diagonal matrix from eigenvalues
R = torch.diag(val)

# Convert complex tensors to real tensors
P = P.real
R = R.real
Q = Q.real

# Reconstruct the original matrix. Note: Here the dot product is not communtative
N = torch.matmul(torch.matmul(P,R),Q)
print("Final Matrix:\n",N)

Initial Matrix:
 [[6 8 5]
 [4 7 1]
 [9 2 6]]
Eigen Values:
 tensor([15.7791+0.j, -1.9133+0.j,  5.1342+0.j])
Eigen Vectors:
 tensor([[ 0.6447+0.j,  0.6712+0.j,  0.0370+0.j],
        [ 0.3699+0.j, -0.2219+0.j, -0.5325+0.j],
        [ 0.6690+0.j, -0.7073+0.j,  0.8456+0.j]])
Final Matrix:
 tensor([[6.0000, 8.0000, 5.0000],
        [4.0000, 7.0000, 1.0000],
        [9.0000, 2.0000, 6.0000]])


### Rank of a Matrix


**Rank of a matrix**: - The rank of a matrix is defined as the maximum number of linearly independent column vectors in the matrix or the maximum number of linearly independent row vectors in the matrix.



**Full Row Rank**:- If the rank of a matrix is equal to the number of row in the matrix, then matrix has a Full Row Rank.

**Full Column Rank**:- If the rank of a matrix is equal to the number of columns in the matrix, then matrix has Full Column Rank.


**Rank Deficient**:-When the rank of a matrix is less than the number of rows and columns in the matrix, then the matrix is Rank Deficient.

**Uses**:-
It is useful in understanding whether we have a chance of solving a system of linear equations or not. Further, if rank is equal to the number of variables we will be able to find a unique solution.


1. Create a random matrix and find the rank of it.

    Refer to the following [link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html) to find the rank of a matrix

In [38]:
# YOUR CODE HERE: To create a matrix
mat = torch.randn(3,3)

# YOUR CODE HERE: To find the rank of a matrix
rank = torch.linalg.matrix_rank(mat)
print("Rank:\n",rank)

Rank:
 tensor(3)


### Singular Value Decomposition

The Singular-Value Decomposition, or SVD is a matrix decomposition method for reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations simpler. The singular value decomposition (SVD) provides another way to factorize a matrix, into singular vectors and singular values. The SVD allows us to discover some of the same kind of information as the eigendecomposition.

Steps to follow for Singular Value Decomposition

  A. Factorize a matrix using SVD

  B. Reconstruct the original matrix

**A. Matrix Factorization:**

In simple terms, SVD is the factorization of a matrix into 3 matrices. So if we have a matrix A, then its SVD is represented by:
<center>
$A = U ∑ V^{T}$
</center>

Where A is an $m$ x $n$ matrix,  

*   $U$ is an $m$ x $m$ orthogonal matrix
*   $∑$ is an $m$ x $n$ diagonal matrix with non-negative real numbers.
*   $V$ is an $n$ x $n$ orthogonal matrix.


$U$ is also referred to as the left singular vectors, $∑$ the singular values, and $V$ the right singular vectors.

**B. Reconstruct the original matrix from SVD:**

The original matrix can be reconstructed from the $U$, Sigma, and $V^{T}$ elements.



1. Create an array of $2$ x $3$ matrix and apply singular value decompostition on it.




> The SVD can be calculated by calling the `svd()` function from `numpy.linalg`.

> The function takes a matrix and returns the $U$, Sigma and $V^{T}$ elements. The Sigma diagonal matrix is returned as a vector of singular values. The $V$ matrix is returned in a transposed form, e.g. $V^{T}$.











In [45]:
# YOUR CODE HERE: Define a matrix
M = torch.randn(2,3)
print("Matrix:\n",M)
# YOUR CODE HERE: To apply ingular Value Decomposition on the matrix
U,S,V = torch.linalg.svd(M)
print("U:\n",U)
print("S:\n",S)
print("V:\n",V)
# YOUR CODE HERE: Create m x n matrix called sigma
sigma = S
# YOUR CODE HERE: Populate sigma with n x n diagonal matrix
sigma = torch.zeros(2,3)
sigma[:2,:2] = torch.diag(S)
print(sigma)
# YOUR CODE HERE: To Reconstruct the original matrix
B = torch.matmul(torch.matmul(U,sigma),V)
print("Reconstruct Matrix:\n",B)

Matrix:
 tensor([[ 1.7785,  0.0403, -0.0139],
        [ 1.1497,  0.6674, -0.3347]])
U:
 tensor([[ 0.8049, -0.5934],
        [ 0.5934,  0.8049]])
S:
 tensor([2.1669, 0.5904])
V:
 tensor([[ 0.9755,  0.1977, -0.0968],
        [-0.2201,  0.8694, -0.4423],
        [-0.0033,  0.4528,  0.8916]])
tensor([[2.1669, 0.0000, 0.0000],
        [0.0000, 0.5904, 0.0000]])
Reconstruct Matrix:
 tensor([[ 1.7785,  0.0403, -0.0139],
        [ 1.1497,  0.6674, -0.3347]])


### Matrix and Vector Norms

**Matrix Norm**: The norm of a matrix is a measure of how large its elements are. It is a way of determining the “size” of a matrix that is not necessarily related to how many rows or columns the matrix has.

The norm of a square matrix A is a non-negative real number denoted $\left \| A \right \|$. There are several
different ways of defining a matrix norm, but they all share the following properties:
1. $\left \| A \right \|$ ≥ 0 for any square matrix A.
2. $\left \| A \right \|$ = 0 if and only if the matrix A = 0.
3. $\left \| kA \right \|$ = |k| $\left \| A \right \|$, for any scalar k.
4. $\left \| A+B \right \|$ ≤ $\left \| A \right \|$ + $\left \| B \right \|$.
5. $\left \| AB \right \|$ ≤ $\left \| A \right \|$ $\left \| B \right \|$.

Below is the formula to calculate 1 norm of a matrix:

$\left \| A \right \|_{1} = \max_{1≤j≤n} (\sum_{i}^{n} \left | a_{ij} \right |)$

By using this formula we compute the sum of absolute values down each column
and then take the largest number.



1. Calculate the 1-norm of a matrix $A =\begin{pmatrix}
    5 & -4 & 2\\
    -1 & 2 & 3\\
    -2 & 1 & 0\\
   \end{pmatrix}$.

   Refer to the following [link ](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) to understand norm function in numpy's linalg module


In [46]:
# Creating a matrix
# YOUR CODE HERE
A = torch.tensor([[5,-4,2],[-1,2,3],[-2,1,0]],dtype=torch.float)

# 1-Norm of a matrix
# The 1-Norm of a matrix is the maximum of the sum of each column
# Pass the matrix to the norm function and specify the order
# YOUR CODE HERE
norm = torch.linalg.norm(A,1)
print("1-Norm:\n",norm)

1-Norm:
 tensor(8.)


**Vector Norm**: The norm of a vector in vector space is a real non-negative value representing intuitively the length, size, or magnitude of the vector.

The most commonly used vector norms belong to the family of $p$-norms, or $l_{p}$-norms, which
are defined by:
<center>
$\left \| x \right \|_{p} = (\sum_{i = 1}^{n} |x_{i}|^{p}) ^ {1/p}$
</center>

It can be shown that for any $p > 0$,  $∥ ⋅ ∥_{p}$ defines a vector norm. The following $p$-norms are of
particular interest:


*   $p = 1$: The $l_{1}$-norm
<center>
$∥ x ∥_{1} =  |x_{1}| +  |x_{2}| +....+ |x_{n}| $
</center>

*   $p = 2$: The $l_{2}$-norm or Euclidean norm
<center>
$\left \| x \right \|_{2}= \sqrt{x_{1}^{2}+x_{2}^{2}+...+x_{n}^{2}}$
</center>

* $p = ∞$: The $l_{∞}$-norm
<center>
$\left \| x \right \|_{∞}= \max_{1\leq i \leq n} |x_{i}|$.
</center>


1. Compute the norm of a given vector $A = [5,12]$.

In [47]:
# Creating a matrix
# YOUR CODE HERE
A = torch.tensor([5,12],dtype=torch.float)

# L2-Norm of a vector
# YOUR CODE HERE
norm = torch.linalg.norm(A,2)
print("L2-Norm:\n",norm)

L2-Norm:
 tensor(13.)


### Matrix Calculus



### 1. Dervatives w.r.t. Scalar

#### Scalar w.r.t Scalar





1. Differentiate the below given scalar function $f(x)$ w.r.t. to a scalar $x$.

  $ f(x) = \cos x + \sin x + x^2 $

In [51]:
# Declaring symbols that can be used as variables in the function
# YOUR CODE HERE
import sympy as sym
x = sym.Symbol('x')

# Defining a function 'f'
# YOUR CODE HERE
f = sym.cos(x) + sym.sin(x) + x**2

# Derivative of the scalar function w.r.t. a scalar x using the 'diff' function of Sympy
# YOUR CODE HERE
df = sym.diff(f,x)
print("Derivative:\n",df)

Derivative:
 2*x - sin(x) + cos(x)


#### Vector w.r.t. Scalar

2. Differentiate the given vector $\vec{y}^{\,} = \begin{pmatrix}
    x^2 + 2x \\
    sinx \\
    cosx \\
   \end{pmatrix}$ w.r.t. a scalar $x$.

  Note: `Vector` is a special case of `Matrix`




In [54]:
# YOUR CODE HERE
y = sym.Matrix([x**2 + 2*x, sym.sin(x), sym.cos(x)])
dy = y.diff(x)
print("Derivative:\n",dy)

Derivative:
 Matrix([[2*x + 2], [cos(x)], [-sin(x)]])


#### Matrix w.r.t. Scalar

3. Find the derivative of the matrix $M = \begin{pmatrix}
    x^2 + 2x & cos(x)\\
    sin(x) & x^3+2x\\
   \end{pmatrix}$ w.r.t. a scalar $x$.




In [55]:
# YOUR CODE HERE
M = sym.Matrix([[x**2 + 2*x, sym.cos(x)],[sym.sin(x), x**3 + 2*x]])
dM = M.diff(x)
print("Derivative:\n",dM)

Derivative:
 Matrix([[2*x + 2, -sin(x)], [cos(x), 3*x**2 + 2]])


Before moving ahead with more questions on derivatives w.r.t. vectors and matrices, you should have knowledge of "Partial Derivatives", "Jacobian Matrix" and "Numerator Layout Notation".

### Partial Derivatives

Let us consider a function $f(x,y) = x^2 + y^2$ we can take a derivative of the changes in the function with respect to either x or y. We call these derivatives with respect to one variable partial derivatives. Let's give this a try by taking the derivative of $f(x,y)$ with respect to x. We write this partial derivative as follows.

$$\frac{\partial f(x,y)}{\partial x} = \frac{\partial (x^2 + y^2)}{\partial x}$$

Since $f(x,y)$ is the sum of several simpler functions we need to take the partial derivative of each of these and sum the result. The first two parts are easy. $\frac{\partial x^2}{\partial x} = 2x$. Notice that we are following the usual rules of differentiation for any function of x here.

Now we need to take the partial derivative of the last part of $f(x,y)$, which does not depend on x at all. In these case we get the following $\frac{\partial y^2}{\partial x} = 0$.
Now we can add up the parts to get the complete partial derivative of $f(x,y)$.

$$\frac{\partial f(x,y)}{\partial x} = 2x + 0 = 2x$$
We can also take the partial derivative of $f(x,y)$ with respect to y. The process proceeds in the following manner $\frac{\partial f(x,y)}{\partial y} = 0 + 2y = 2y$

### Jacobian Matrix

To test for functional dependence (both linear and non linear equations) between different equations we use Jacobian determinant shown by |j|. The Jacobian matrix is the first order derivatives of a vector valued function. Vector valued functions are defined as $f: \mathbb{R}^n \to \mathbb{R}^m$.

Given $x \in \mathbb{R}^n$ and $f_j : \mathbb{R}^n \to \mathbb{R}$ we have

$$f(x) = \begin{bmatrix}
    f_1(x) \\
    f_2(x) \\
    \vdots \\
    f_m(x)
\end{bmatrix}$$

 We could then define the jaccobian  as

 $$J(x) = \begin{bmatrix}
    \frac{\partial f_1}{\partial x_1} & \frac{\partial f_1}{\partial x_2}  & \dots  & \frac{\partial f_1}{\partial x_n} \\
    \frac{\partial f_2}{\partial x_1} & \frac{\partial f_2}{\partial x_2}  & \dots  & \frac{\partial f_2}{\partial x_n}  \\
    \vdots & \vdots & \ddots & \vdots \\
    \frac{\partial f_m}{\partial x_1} & \frac{\partial f_m}{\partial x_2}  & \dots  & \frac{\partial f_m}{\partial x_n}
\end{bmatrix} $$

Hence each row represents the derivative of a real valued function with input vectors. Note that using shape convention we must reshape that to have the same output as the vector input.

Let's find the derviate of function $f(x, y) = x + sin(y) $ with respect to x and y

In [57]:
# Defining x and y as symbols
# YOUR CODE HERE
x, y = sym.symbols('x y')

# Defining the function f(x, y)
# YOUR CODE HERE
f = x + sym.sin(y)
print(f)

x + sin(y)


In [58]:
# Derivate w.r.t to 'x'
# YOUR CODE HERE
df_dx = sym.diff(f,x)
print("Derivative w.r.t x:\n",df_dx)

# Derivate w.r.t to 'y'
# YOUR CODE HERE
df_dy = sym.diff(f,y)
print("Derivative w.r.t y:\n",df_dy)

Derivative w.r.t x:
 1
Derivative w.r.t y:
 cos(y)


If we organize these partials into a horizontal vector, we get the gradient of $f(x, y)$, or $\Delta f(x, y)$ :

$ \Delta f(x,y)  = [\frac{\partial f(x,y)}{\partial x}, \frac{\partial f(x,y)}{\partial y}] = [1, cos(y)] $

In [61]:
# YOUR CODE HERE
vec_par_df = sym.Matrix([df_dx,df_dy])
print("Gradient of f(x,y):\n",vec_par_df)

Gradient of f(x,y):
 Matrix([[1], [cos(y)]])


Now let's find the derviate of function $g(x, y) = sin(x) + y $ with respect to x and y

In [62]:
# Defining the function g(x, y)
# YOUR CODE HERE
g = sym.sin(x) + y
print(g)

y + sin(x)


In [63]:
# Derivate w.r.t to 'x'
# YOUR CODE HERE
df_dx = sym.diff(g,x)
print("Derivative w.r.t x:\n",df_dx)

# Derivate w.r.t to 'y'
# YOUR CODE HERE
df_dy = sym.diff(g,y)
print("Derivative w.r.t y:\n",df_dy)

Derivative w.r.t x:
 cos(x)
Derivative w.r.t y:
 1


If we organize these partials into a horizontal vector, we get the gradient of $g(x, y)$, or  $Δg(x,y)$:

$ \Delta g(x,y)  = [\frac{\partial g(x,y)}{\partial x}, \frac{\partial g(x,y)}{\partial y}] = [cos(x), 1] $

In [64]:
# YOUR CODE HERE
vec_par_dg = sym.Matrix([df_dx,df_dy])
print("Gradient of g(x,y):\n",vec_par_dg)

Gradient of g(x,y):
 Matrix([[cos(x)], [1]])


If we organize the gradients of $f(x, y)$ and $g(x, y)$ into a single matrix, we move from vector calculus into matrix calculus. This matrix, and organization of the gradients of multiple functions with multiple variables, is known as the Jacobian matrix.

$ J = \begin{bmatrix}
\Delta f(x,y) \\
\Delta g(x,y) \end{bmatrix} =\begin{bmatrix}
\frac{\partial f(x, y)}{\partial x} & \frac{\partial f(x, y)}{\partial y}\\
\frac{\partial g(x, y)}{\partial x} & \frac{\partial g(x, y)}{\partial y}
\end{bmatrix} = \begin{bmatrix}
1 & cos(y) \\
cos(x) & 1
\end{bmatrix} $

To know more about the Jacobian Matrix read [here](https://towardsdatascience.com/step-by-step-the-math-behind-neural-networks-d002440227fb)

In [65]:
# YOUR CODE HERE
J = sym.Matrix([vec_par_df,vec_par_dg])
print("Jacobian Matrix:\n",J)

Jacobian Matrix:
 Matrix([[1], [cos(y)], [cos(x)], [1]])


### Numerator Layout Notation:

This approach is used when we have to find the derivative w.r.t. a vector. Using Numerator Layout Notation, we find the partial derivative of a scalar, matrix, or a vector w.r.t. each element of the vector.
<br>Suppose, there is a vector $\vec{x}^{\,}$ = ($x_{1}$, $x_{2}$, $x_{3}$,.... $x_{n}$) w.r.t. which we have to find the derivative of a scalar function or a matrix.
<br>For this, we will take the partial derivative of the scalar function or a matrix w.r.t. each element of the vector as shown below:

$\frac{\partial}{\partial_x}$ = $\left (\frac{\partial}{\partial_(x_{1})}, \frac{\partial}{\partial_(x_{2})}, \frac{\partial}{\partial_(x_{3})}  \right )$


### 2. Dervatives w.r.t. Vector

#### Scalar by Vector

1. Given a scalar function $y = \tan(x^2+yz)$. Find the derivative of $y$ w.r.t. the below vector:

  $\vec{v}^{\,}(x,y,z)$ = $xyz$

  Hint: Apply numerator layout notation where we take derivative of the function w.r.t. every element of the vector.



In [72]:
# Defining symbols that will be used as variables in the function
# YOUR CODE HERE
x, y, z = sym.symbols('x y z')
# Defining a scalar function using the symbols x, y and z
# YOUR CODE HERE
y1 = sym.tan(x**2 + y*z)
v = sym.Matrix([x,y,z])

Differentiating the scalar function w.r.t. each element of the vector i.e. x, y, and z

In [78]:
# YOUR CODE HERE
dy1_dv = y1.diff(v)
print("Derivative:\n",dy1_dv)

Derivative:
 Matrix([[2*x*(tan(x**2 + y*z)**2 + 1)], [z*(tan(x**2 + y*z)**2 + 1)], [y*(tan(x**2 + y*z)**2 + 1)]])


#### Matrix by Vector

2. Find the derivative of the below matrix $M$ w.r.t. vector $\vec{v}^{\,}$ = $ xyz$:

\begin{pmatrix}
    x+x^2z & cosx\\
    xyz & 3y+x^2\\
   \end{pmatrix}



In [84]:
# Defining the matrix M
# YOUR CODE HERE
M = sym.Matrix([[x + x**2*z, sym.cos(x)],[x*y*z, 3*y + x**2]])

# Differentiating matrix 'M' w.r.t. each element of the vector v that are x, y, z
# YOUR CODE HERE
dM_dv = M.diff(v)
print("Derivative:\n",dM_dv)

# Result -> Organizing the result of partial derivatives into a single matrix
# YOUR CODE HERE
final_par_df = [dM_dv[0], dM_dv[1], dM_dv[2]]
print("Final Derivative:\n",final_par_df)

Derivative:
 [[[[2*x*z + 1, -sin(x)], [y*z, 2*x]]], [[[0, 0], [x*z, 3]]], [[[x**2, 0], [x*y, 0]]]]
Final Derivative:
 [[[[2*x*z + 1, -sin(x)], [y*z, 2*x]]], [[[0, 0], [x*z, 3]]], [[[x**2, 0], [x*y, 0]]]]


#### Vector by Vector

3. Find the derivative of vector $\vec{v}^{\,}$ = $\begin{pmatrix}
   cosx+x\\
    x^2+y^2\\
    3x^3-z^2y\\
   \end{pmatrix}$ w.r.t. a vector $\vec{k}^{\,}$ = $xyz$

In [87]:
# Defining the vector v
# YOUR CODE HERE
v = sym.Matrix([sym.cos(x) + x, x**2 + y**2, 3*x**3 - z**2*y])
k = sym.Matrix([x,y,z])

# Vector k = xyz indicates that we have to differentiate vector 'v' w.r.t. x, y, and z
# YOUR CODE HERE
dv_dk = v.diff(k)
print("Derivative:\n",dv_dk)

# Result -> Organizing the result of partial derivatives into a single matrix
# YOUR CODE HERE
final_par_dv = [dv_dk[0], dv_dk[1], dv_dk[2]]
print("Final Derivative:\n",final_par_dv)

Derivative:
 [[[[1 - sin(x)], [2*x], [9*x**2]]], [[[0], [2*y], [-z**2]]], [[[0], [0], [-2*y*z]]]]
Final Derivative:
 [[[[1 - sin(x)], [2*x], [9*x**2]]], [[[0], [2*y], [-z**2]]], [[[0], [0], [-2*y*z]]]]


### 3. Dervatives w.r.t. Matrix

#### Scalar by Matrix
To find the derivative of a scalar w.r.t. a matrix, we have to find the derivative of the scalar function w.r.t. every element of the matrix to get the final result.
<br> Further, let us understand with th help of a question.

1. Find the derivative of a scalar $y = (sinx_{1}+2x_{2}+x_{3}^2+7x_{4})$ w.r.t. a matrix $M = \begin{pmatrix}
   x_{1} & x_{2}\\
    x_{3} & x_{4}\\
   \end{pmatrix}$.

In [88]:
# Defining the symbols for the matrix M
# YOUR CODE HERE
x1, x2, x3, x4 = sym.symbols('x1 x2 x3 x4')
# Defining a scalar function using the symbols declared above which are used as variables
# YOUR CODE HERE
y = sym.sin(x1) + 2*x2 + x3**2 + 7*x4
# Defining a matrix
# YOUR CODE HERE
M = sym.Matrix([[x1, x2],[x3, x4]])
# Differentiation of scalar function w.r.t. every element of the matrix
# YOUR CODE HERE
dy_dm = y.diff(M)
print("Derivative:\n",dy_dm)
# Organizing the result of partial derivatives into a single matrix
# YOUR CODE HERE
final_par_dy = [dy_dm[0], dy_dm[1], dy_dm[2], dy_dm[3]]
print("Final Derivative:\n",final_par_dy)

Derivative:
 Matrix([[cos(x1), 2], [2*x3, 7]])
Final Derivative:
 [cos(x1), 2, 2*x3, 7]


#### Matrix by Matrix
Here, we have to find the derivative of the given matrix w.r.t. each element of the matrix by which we have to differentiate.
<br> Let us solve a question to understand derivative of a matrix wr.r.t. a matrix.

2. Find the derivative of a matrix $A$ = $\begin{pmatrix}
   x_{1}^2+x_{2}^2+x_{2} & x_{2}^2+x_{4}^2\\
    sinx_{2}+x_{3}^2 & x_{1}+x_{3}+x_{4}\\
   \end{pmatrix}$  w.r.t. a matrix $M = \begin{pmatrix}
   x_{1} & x_{2}\\
    x_{3} & x_{4}\\
   \end{pmatrix}$.

In [95]:
# Defining the matrix A
# YOUR CODE HERE
A = sym.Matrix([[x1**2 + x2**2 + x2, x2**2 + x4**2],[sym.sin(x2) + x3**2, x1 + x3 + x4]])

# Defining matrix M
# YOUR CODE HERE
M = sym.Matrix([[x1, x2],[x3, x4]])

# Differentiating matrix A w.r.t. each element of matrix M
# YOUR CODE HERE
dA_dm = A.diff(M)
print("Derivative:\n",dA_dm)
print('Shape:', dA_dm.shape)

dA_dx1 = dA_dm[0, 0]
dA_dx2 = dA_dm[0, 1]
dA_dx3 = dA_dm[1, 0]
dA_dx4 = dA_dm[1, 1]

print("\nPartial derivative w.r.t x1:\n", dA_dx1)
print("\nPartial derivative w.r.t x2:\n", dA_dx2)
print("\nPartial derivative w.r.t x3:\n", dA_dx3)
print("\nPartial derivative w.r.t x4:\n", dA_dx4)

Derivative:
 [[[[2*x1, 0], [0, 1]], [[2*x2 + 1, 2*x2], [cos(x2), 0]]], [[[0, 0], [2*x3, 1]], [[0, 2*x4], [0, 1]]]]
Shape: (2, 2, 2, 2)

Partial derivative w.r.t x1:
 [[2*x1, 0], [0, 1]]

Partial derivative w.r.t x2:
 [[2*x2 + 1, 2*x2], [cos(x2), 0]]

Partial derivative w.r.t x3:
 [[0, 0], [2*x3, 1]]

Partial derivative w.r.t x4:
 [[0, 2*x4], [0, 1]]


#### Vector by Matrix
As vector is a special case of matrix, so, we will consider the vector as a matrix while finding the derivative using Python.

3. Find the derivative of vector $\vec{m}^{\,}$ = $\begin{pmatrix}
   sinx_{1}+x_{2}\\
    x_{3}^2+x_{2}^2\\
    2x_{2}+x_{4}\\
   \end{pmatrix}$ w.r.t. the matrix $M = \begin{pmatrix}
   x_{1} & x_{2}\\
    x_{3} & x_{4}\\
   \end{pmatrix}$.

In [99]:
# YOUR CODE HERE
m = sym.Matrix([sym.sin(x1) + x2, x3**2 + x2**2, 2*x2 + x4])
M = sym.Matrix([[x1, x2],[x3, x4]])

dm_dm = m.diff(M)
print("Derivative:\n",dm_dm)
print('Shape:', dm_dm.shape)

dm_dx1 = dm_dm[0, 0]
dm_dx2 = dm_dm[0, 1]
dm_dx3 = dm_dm[1, 0]
dm_dx4 = dm_dm[1, 1]

print("\nPartial derivative w.r.t x1:\n", dm_dx1)
print("\nPartial derivative w.r.t x2:\n", dm_dx2)
print("\nPartial derivative w.r.t x3:\n", dm_dx3)
print("\nPartial derivative w.r.t x4:\n", dm_dx4)

Derivative:
 [[[[cos(x1)], [0], [0]], [[1], [2*x2], [2]]], [[[0], [2*x3], [0]], [[0], [0], [1]]]]
Shape: (2, 2, 3, 1)

Partial derivative w.r.t x1:
 [[cos(x1)], [0], [0]]

Partial derivative w.r.t x2:
 [[1], [2*x2], [2]]

Partial derivative w.r.t x3:
 [[0], [2*x3], [0]]

Partial derivative w.r.t x4:
 [[0], [0], [1]]


### Question for practice (Ungraded)

Q. The derivative of a matrix $A = \begin{pmatrix}
    x^4 & x^2+2x\\
    xyz & cos(x)\\
   \end{pmatrix}$ w.r.t. a scalar $x$.

a) $\begin{pmatrix} 4x^2 & 2\\ 1 & sin(x)\\ \end{pmatrix} $

b) $\begin{pmatrix}
    x^3 & x^2+2x\\
    xyz & cos(x)\\
   \end{pmatrix}$

c) $\begin{pmatrix}
    4x^3 & 2x+2\\
    yz & -sin(x)\\
   \end{pmatrix}$

d) $\begin{pmatrix}
    4x^3 & x\\
    1 & -cos(x)\\
   \end{pmatrix}$

Ans) c

### Please answer the questions below to complete the experiment:




#### Consider the below matrix 'A' and the values of $σ_{1}$, $σ_{2}$, $σ_{3}$ given below for answering Q.1

<br>
$A = \begin{pmatrix}
   4 & 11 & 14\\
    8 & 7 & -2\\
   \end{pmatrix}$

<br>
<br>

A. $σ_{1} = {{360}}$, $σ_{2} = {{90}}$, $σ_{3} = 0$

B. $σ_{1} = {6\sqrt{10}}$, $σ_{2} = {3\sqrt{10}}$, $σ_{3} = 0$

C. $σ_{1} = {-6\sqrt{10}}$, $σ_{2} = {3\sqrt{10}}$, $σ_{3} = {{0}}$

D. $σ_{1} = {6\sqrt{10}}$, $σ_{2} = {{0}}$, $σ_{3} = {-3\sqrt{10}}$




In [ ]:
#@title Q.1. Find the singular values for the matrix $A^T A$.  { run: "auto", form-width: "500px", display-mode: "form" }
Answer1 = "" #@param ["","Only A", "Only B", "Only C", "Only D", "None of the above"]


Consider the below column values $v_{1}$, $v_{2}$, $v_{3}$ and $v_{4}$ and answer Q.2

A. $v_{1} = \begin{pmatrix}
   1/3\\
    2/3\\
     2/3\\
   \end{pmatrix}$

B.  $v_{2} = \begin{pmatrix}
   -2/3\\
    -1/3\\
     2/3\\
   \end{pmatrix}$

C.  $v_{3} = \begin{pmatrix}
   2/3\\
    -2/3\\
     1/3\\
   \end{pmatrix}$

D. $v_{4} = \begin{pmatrix}
   2/3\\
    2/3\\
     1/3\\
   \end{pmatrix}$

In [ ]:
#@title Q.2. Find the normalized eigenvector corresponding to the highest eigenvalue obtained in question 1 by computing $A^T A$? { run: "auto", form-width: "500px", display-mode: "form" }
Answer2 = "" #@param ["","Only A", "Only B", "Only C", "Only D", "None of the above"]


In [ ]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [ ]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "" #@param {type:"string"}


In [ ]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "" #@param ["","Yes", "No"]


In [ ]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")