<a href="https://colab.research.google.com/github/UpendraVishwanathYS/IISc_Deep_Learning_Course_Assignment/blob/main/M1_AST_01_Linear_Algebra_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Programme in Deep Learning (Foundations and Applications)
## A Program by IISc and TalentSprint
### Assignment 2: Linear Algebra

## Learning Objectives

At the end of the assignment, you will be able to
* understand matrix, types of matrix, vectors and its related operations



### Setup Steps:

In [ ]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "" #@param {type:"string"}

In [ ]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "" #@param {type:"string"}

In [1]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython
import warnings
warnings.filterwarnings("ignore")

ipython = get_ipython()

notebook= "M1_AST_01_Linear_Algebra_A" #name of the notebook

def setup():
    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    ipython.magic("notebook -e"+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getAnswer1() and getAnswer2() and getComplexity() and getAdditional() and getConcepts() and getComments() and getMentorSupport():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "answer1" : Answer1, "answer2" : Answer2, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook,
              "feedback_experiments_input" : Comments,
              "feedback_mentor_support": Mentor_support}
      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://learn-iisc.talentsprint.com/notebook_submissions")
        #print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
        return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None


# def getWalkthrough():
#   try:
#     if not Walkthrough:
#       raise NameError
#     else:
#       return Walkthrough
#   except NameError:
#     print ("Please answer Walkthrough Question")
#     return None

def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None


def getMentorSupport():
  try:
    if not Mentor_support:
      raise NameError
    else:
      return Mentor_support
  except NameError:
    print ("Please answer Mentor support Question")
    return None

def getAnswer1():
  try:
    if not Answer1:
      raise NameError
    else:
      return Answer1
  except NameError:
    print ("Please answer Question 1")
    return None

def getAnswer2():
  try:
    if not Answer2:
      raise NameError
    else:
      return Answer2
  except NameError:
    print ("Please answer Question 2")
    return None


def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()
else:
  print ("Please complete Id and Password cells before running setup")



Please complete Id and Password cells before running setup


### Importing required packages

In [2]:
import numpy as np
from math import *
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from numpy import linalg as la
from numpy.linalg import eig

### Types of Matrix

**Square Matrix**: In square matrix, the number of rows are equal to the number of columns.

1. Create a square matrix with elements 61 to 69.

In [3]:
A = np.array([[61,62,63],[64,65,66],[67,68,69]])
print(A)

[[61 62 63]
 [64 65 66]
 [67 68 69]]



**Upper Triangular Matrix**: It is a type of square matrix, where all the values below the main diagonal are 0.

**Lower Triangular Matrix**: It is a type of square matrix, where all the values above the main diagonal are 0.


2. Create an upper and lower triangular matrix of size 6x6 with random values.

In [4]:
matrix = np.random.rand(6,6)
print("Original Matrix:\n",matrix)

# Upper triangular matrix
# YOUR CODE HERE
upper_triangular = np.triu(matrix)
print("Upper Triangular Matrix:\n",upper_triangular)

# Lower triangular matrix
# YOUR CODE HERE
lower_triangular = np.tril(matrix)
print("Lower Triangular Matrix:\n",lower_triangular)

Original Matrix:
 [[0.14968969 0.99324259 0.97267662 0.56685595 0.20732235 0.68502307]
 [0.50354523 0.2520708  0.15989531 0.46619504 0.30993267 0.67138129]
 [0.35263604 0.84088111 0.29555027 0.68155078 0.63787136 0.12144665]
 [0.17160585 0.04440606 0.39770941 0.91888161 0.48871643 0.05091419]
 [0.03031404 0.2118473  0.76938658 0.41264032 0.76241231 0.40436748]
 [0.21448369 0.97752722 0.85888528 0.93972766 0.42677762 0.0722502 ]]
Upper Triangular Matrix:
 [[0.14968969 0.99324259 0.97267662 0.56685595 0.20732235 0.68502307]
 [0.         0.2520708  0.15989531 0.46619504 0.30993267 0.67138129]
 [0.         0.         0.29555027 0.68155078 0.63787136 0.12144665]
 [0.         0.         0.         0.91888161 0.48871643 0.05091419]
 [0.         0.         0.         0.         0.76241231 0.40436748]
 [0.         0.         0.         0.         0.         0.0722502 ]]
Lower Triangular Matrix:
 [[0.14968969 0.         0.         0.         0.         0.        ]
 [0.50354523 0.2520708  0.     

**Diagonal Matrix**: In a diagonal matrix, all the values are zero except the diagonal values

3. Create a diagonal matrix of size 3x3 with integer valules and do the following:

  i). Create a diagonal matrix with the values above the diagonal elements.
  
  ii). Create a diagonal matrix with the values below the diagonal elements.





In [5]:
M = np.array([np.arange(73,76),np.arange(32,35), np.arange(57,60)])
print("Matrix:\n",M)

# Diagonal Matrix
# YOUR CODE HERE
diagonal_matrix = np.diag(np.diag(M))
print("Diagonal Matrix:\n",diagonal_matrix)

# Using k=1 for getting the diagonal matrix with the values above the diagonal elements
# YOUR CODE HERE
k = 1
above_diagonal_matrix = np.diag(np.diag(M, k=k))
print("Diagonal Matrix with values above the diagonal elements:\n",above_diagonal_matrix)

# Using k=-1 for getting the diagonal matrix with the values below the diagonal elements
# YOUR CODE HERE
k = -1
below_diagonal_matrix = np.diag(np.diag(M, k=k))
print("Diagonal Matrix with values below the diagonal elements:\n",below_diagonal_matrix)

Matrix:
 [[73 74 75]
 [32 33 34]
 [57 58 59]]
Diagonal Matrix:
 [[73  0  0]
 [ 0 33  0]
 [ 0  0 59]]
Diagonal Matrix with values above the diagonal elements:
 [[74  0]
 [ 0 34]]
Diagonal Matrix with values below the diagonal elements:
 [[32  0]
 [ 0 58]]


Here all the non-diagonal elements are zero.

**Identity Matrix**: A matrix of size nxn where all diagonal values are 1 and other values are 0 is an identity matrix.

4. Create a 4x4 identity matrix with integer numbers.

In [6]:
# YOUR CODE HERE
identity_matrix = np.identity(4, dtype=int)
print("Identity Matrix:\n",identity_matrix)

Identity Matrix:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


**Null Matrix**: A null matrix has all the values as zero.

5. Create a null matrix of integers with shape 6x6.

In [7]:
# YOUR CODE HERE
null_matrix = np.zeros((6,6), dtype=int)
print("Null Matrix:\n",null_matrix)

Null Matrix:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### Matrix Transpose, Inverse, and Determinant

**Transpose**: Transpose operation flips the matrix over its diagonal i.e. replacing rows with coloums and vice-versa.

1. Create a matrix and find its transpose.

In [8]:
# Creating a matrix
# YOUR CODE HERE
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n",matrix)

# Matrix transpose
# YOUR CODE HERE
transpose = np.transpose(matrix)
print("Transpose:\n",transpose)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


**Inverse**: This operation helps to create a matrix such that when it is multiplied by the original matrix, the result is an identity matrix.

2. Find the inverse of a matrix.

In [9]:
# Create a matrix
# YOUR CODE HERE
matrix = np.array([[1,2],[3,4]])
print("Matrix:\n",matrix)

# Finding the inverse
# YOUR CODE HERE
inverse = np.linalg.inv(matrix)
print("Inverse:\n",inverse)

Matrix:
 [[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


3. Create 3x3 matrix and find the inverse of it.

In [12]:
# Create a matrix
# YOUR CODE HERE
matrix = np.random.rand(3,3)
print("Matrix:\n",matrix)

# Finding Inverse
# YOUR CODE HERE
inverse = np.linalg.inv(matrix)
print("Inverse:\n",inverse)

Matrix:
 [[0.45693254 0.96165349 0.59029219]
 [0.57827672 0.04646196 0.51659895]
 [0.07439535 0.08756021 0.2972679 ]]
Inverse:
 [[ 0.27356285  2.03882427 -4.08633597]
 [ 1.16201199 -0.80023602 -0.91676738]
 [-0.41073328 -0.27453421  4.65666407]]


**Determinant**: Determinant of a matrix is a scalar value that helps to characterize the properties of a matrix.

4. Create a matrix of size 3x3 and find the determinant of it.

  To know more about Python libraries, click [here](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html)




In [16]:
# YOUR CODE HERE
matrix = np.random.rand(3,3)
print("Matrix:\n",matrix)

# Finding the determinant
# YOUR CODE HERE
determinant = np.linalg.det(matrix)
print("Determinant:\n",determinant)

Matrix:
 [[0.29017084 0.27130905 0.64592354]
 [0.43347034 0.37285211 0.03447622]
 [0.84859674 0.93574913 0.48954725]]
Determinant:
 0.051596164142637874


\5. Create a 4x4 matrix and slice the rows and columns to get the middle sub-matrix and find its determinant.

In [15]:
# Create 4x4 matrix
# YOUR CODE HERE
matrix = np.random.rand(4,4)
print("Matrix:\n",matrix)

# Slicing of rows and columns
# YOUR CODE HERE
sub_matrix = matrix[1:3,1:3]
print("Sub-Matrix:\n",sub_matrix)

# Finding the determinant
# YOUR CODE HERE
determinant_sub = np.linalg.det(sub_matrix)
print("Determinant:\n",determinant_sub)

Matrix:
 [[0.1671623  0.09905488 0.76539431 0.00335946]
 [0.20606703 0.06899027 0.14228108 0.4455865 ]
 [0.25114237 0.48808203 0.45659069 0.39896732]
 [0.24104044 0.65327492 0.87901641 0.24020542]]
Sub-Matrix:
 [[0.06899027 0.14228108]
 [0.48808203 0.45659069]]
Determinant:
 -0.037944521941969504



### Matrix Operations and Functions


### Addition

1. Create matrix and add a scalar to it.





In [17]:
# Create a matrix
# YOUR CODE HERE
matrix = np.random.rand(3,3)
print("Matrix:\n",matrix)

# Scalar Addition
# YOUR CODE HERE
scalar = 5
addition = matrix + scalar
print("Addition:\n",addition)

Matrix:
 [[0.91464831 0.14000632 0.82891472]
 [0.71231949 0.19045058 0.49553057]
 [0.71172367 0.36259411 0.10753156]]
Addition:
 [[5.91464831 5.14000632 5.82891472]
 [5.71231949 5.19045058 5.49553057]
 [5.71172367 5.36259411 5.10753156]]


2. Create two matrices as matrix1 & matrix2. Then, perform addition operation on them.










In [19]:
# Creating matrices
# YOUR CODE HERE
matrix1 = np.random.rand(3,3)
matrix2 = np.random.rand(3,3)
print("Matrix1:\n",matrix1)
print("Matrix2:\n",matrix2)

# Matrix Addition
# YOUR CODE HERE
addition = matrix1 + matrix2
print("Addition:\n",addition)

Matrix1:
 [[0.65673043 0.45861984 0.6542005 ]
 [0.59908203 0.16540724 0.10366273]
 [0.091142   0.73990002 0.19620045]]
Matrix2:
 [[0.34888933 0.288286   0.8550391 ]
 [0.39062189 0.92303967 0.6975966 ]
 [0.79203524 0.90636618 0.73788453]]
Addition:
 [[1.00561977 0.74690584 1.5092396 ]
 [0.98970392 1.08844691 0.80125933]
 [0.88317724 1.64626621 0.93408498]]


### Subtraction

3. Create a matrix of size 3x6 and subtract a scalar from it.



In [20]:
# Creating matrices
# YOUR CODE HERE
matrix = np.random.rand(3,6)
print("Matrix:\n",matrix)

# Scalar Substraction
# YOUR CODE HERE
scalar = 5
subtraction = matrix - scalar
print("Subtraction:\n",subtraction)

Matrix:
 [[0.65853318 0.45824192 0.29360513 0.27594816 0.64796841 0.29869828]
 [0.68458416 0.80034677 0.57796566 0.96340824 0.70805294 0.31582114]
 [0.73938938 0.32490516 0.32783925 0.99363353 0.47517569 0.04187108]]
Subtraction:
 [[-4.34146682 -4.54175808 -4.70639487 -4.72405184 -4.35203159 -4.70130172]
 [-4.31541584 -4.19965323 -4.42203434 -4.03659176 -4.29194706 -4.68417886]
 [-4.26061062 -4.67509484 -4.67216075 -4.00636647 -4.52482431 -4.95812892]]


4. Create two matrices of size 2x3 and subtract second matrix from the first one.

In [21]:
# Creating matrices
# YOUR CODE HERE
matrix1 = np.random.rand(2,3)
matrix2 = np.random.rand(2,3)
print("Matrix1:\n",matrix1)
print("Matrix2:\n",matrix2)

# Matrix Subtraction
# YOUR CODE HERE
subtraction = matrix1 - matrix2
print("Subtraction:\n",subtraction)

Matrix1:
 [[0.92231003 0.85690841 0.73315361]
 [0.52375016 0.90120817 0.34534944]]
Matrix2:
 [[0.51977699 0.85079505 0.57274489]
 [0.87509645 0.99033531 0.64511154]]
Subtraction:
 [[ 0.40253304  0.00611336  0.16040873]
 [-0.35134628 -0.08912714 -0.2997621 ]]


### Division

5. Create a 4x3 matrix and divide it by a scalar.






In [22]:
# Creating matrix
# YOUR CODE HERE
matrix = np.random.rand(4,3)
print("Matrix:\n",matrix)

# Scalar Division
# YOUR CODE HERE
scalar = 5
division = matrix / scalar
print("Division:\n",division)

Matrix:
 [[0.07323684 0.57179597 0.94623228]
 [0.11716094 0.35468099 0.22915826]
 [0.48126658 0.41965633 0.87642768]
 [0.16774674 0.40589874 0.72333666]]
Division:
 [[0.01464737 0.11435919 0.18924646]
 [0.02343219 0.0709362  0.04583165]
 [0.09625332 0.08393127 0.17528554]
 [0.03354935 0.08117975 0.14466733]]


6. Create two matrices and divide the first matrix by the second one.

In [23]:
# Creating matrices
# YOUR CODE HERE
matrix1 = np.random.rand(4,3)
matrix2 = np.random.rand(4,3)
print("Matrix1:\n",matrix1)
print("Matrix2:\n",matrix2)

# Matrix Division
# YOUR CODE HERE
division = matrix1 / matrix2
print("Division:\n",division)

Matrix1:
 [[0.43680988 0.42004583 0.32872311]
 [0.86515926 0.71929542 0.53692739]
 [0.79700945 0.68766712 0.36503598]
 [0.25094926 0.54249598 0.1093662 ]]
Matrix2:
 [[0.09913944 0.01285743 0.51007522]
 [0.09600652 0.07692463 0.34962819]
 [0.63860943 0.07789084 0.8921423 ]
 [0.85374465 0.07036363 0.16064855]]
Division:
 [[ 4.40601542 32.66950745  0.64446006]
 [ 9.01146401  9.35065186  1.53570968]
 [ 1.24803896  8.82860008  0.40916788]
 [ 0.29393948  7.70989233  0.68077926]]


### Multiplication

7. Create a matrix and mulitply it by a Scalar.




In [24]:
# Creating matrix
# YOUR CODE HERE
matrix = np.random.rand(4,3)
print("Matrix:\n",matrix)

# Scalar Multiplication
# YOUR CODE HERE
scalar = 5
multiplication = matrix * scalar
print("Multiplication:\n",multiplication)

# Scalar Product
# YOUR CODE HERE
scalar_product = np.dot(matrix, scalar)
print("Scalar Product:\n",scalar_product)

Matrix:
 [[0.13833988 0.25163917 0.88427537]
 [0.20466674 0.21839837 0.56994962]
 [0.10024733 0.42371766 0.92662681]
 [0.30822025 0.52529823 0.60020297]]
Multiplication:
 [[0.69169938 1.25819584 4.42137683]
 [1.02333369 1.09199186 2.84974811]
 [0.50123666 2.11858829 4.63313406]
 [1.54110126 2.62649115 3.00101483]]
Scalar Product:
 [[0.69169938 1.25819584 4.42137683]
 [1.02333369 1.09199186 2.84974811]
 [0.50123666 2.11858829 4.63313406]
 [1.54110126 2.62649115 3.00101483]]


Multiplication of two matrices is shown in the below diagram:



$A.B = \begin{bmatrix}
a & b\\
c & d\\
\end{bmatrix} \begin{bmatrix}
e & f\\
g & h\\
\end{bmatrix} = \begin{bmatrix}
ae+ bg & af+bh\\
ce+dg & cf+dh\\
\end{bmatrix}$

8. Create two matrices and multiply them.

  Note: Here, the corresponding elements are not multiplied. The multiplication rules are different from addition, subtraction, and division.

In [30]:
# Creating matrices
# YOUR CODE HERE
matrix1 = np.random.rand(4,3)
matrix2 = np.random.rand(3,4)
print("Matrix1:\n",matrix1)
print("Matrix2:\n",matrix2)

# Matrix Multiplication
# YOUR CODE HERE
multiplication = np.matmul(matrix1, matrix2)
print("Multiplication:\n",multiplication)

# Dot Product
# YOUR CODE HERE
dot_product = np.dot(matrix1, matrix2)
print("Dot Product:\n",dot_product)

Matrix1:
 [[0.61574332 0.26191271 0.9699254 ]
 [0.47547399 0.92688099 0.83425556]
 [0.03686396 0.50424827 0.35322243]
 [0.91289921 0.25115217 0.83739885]]
Matrix2:
 [[0.7006764  0.0359732  0.89547226 0.20611202]
 [0.10763096 0.14091212 0.2170566  0.19911797]
 [0.92048745 0.37901649 0.22905229 0.92940472]]
Multiplication:
 [[1.35243089 0.42667466 0.83039458 1.08051687]
 [1.20083627 0.46390971 0.81804756 1.05792062]
 [0.40523925 0.20625794 0.22336747 0.43628959]
 [1.43749382 0.38561827 1.06379828 1.01645085]]
Dot Product:
 [[1.35243089 0.42667466 0.83039458 1.08051687]
 [1.20083627 0.46390971 0.81804756 1.05792062]
 [0.40523925 0.20625794 0.22336747 0.43628959]
 [1.43749382 0.38561827 1.06379828 1.01645085]]


### Please answer the questions below to complete the experiment:




Consider the statements given below and answer Q1.


A. Every skew-symmetric matrix of odd order is non-singular

B. If determinant of a square matrix is non-zero, then it is non singular

C. Adjoint of symmetric matrix is symmetric

D. Adjoint of a diagonal matrix is diagonal

In [ ]:
#@title Q.1. Which of the above statements is/are False?
Answer1 = "" #@param ["","Only A","Both A & B","Only B", "Only C", "Only D", "Both B & C"]


Consider the matrix A and the values of a, b, and c given below for answering Q.2.

$A = \begin{bmatrix}
0 & 2b & c   \\
a & b & -c   \\
a & -b & c   \\
\end{bmatrix}$

<br>

A). a = $\pm \frac{1}{\sqrt{6}} $, b = $\pm \frac{1}{\sqrt{2}}$ , c = $\pm \frac{1}{\sqrt{2}} $


<br>

B). a = $\pm \frac{1}{\sqrt{6}} $, b = $\pm \frac{1}{\sqrt{3}}$ , c = $\pm \frac{1}{\sqrt{2}} $


<br>

C). a = $\pm \frac{1}{\sqrt{2}} $, b = $\pm \frac{1}{\sqrt{6}}$ , c = $\pm \frac{1}{\sqrt{3}} $

<br>

D). a = $\pm \frac{1}{\sqrt{2}} $, b = $\pm \frac{1}{\sqrt{2}}$ , c = $\pm \frac{1}{\sqrt{2}} $

In [ ]:
#@title Q.2. If 'A' is an orthogonal matrix, then, what will be the values of a, b, and c.
Answer2 = "" #@param ["","Only A","Only B","Only C","Only D", "None of the above"]


In [ ]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [ ]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "" #@param {type:"string"}


In [ ]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "" #@param ["","Yes", "No"]


In [ ]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")